### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by lsolesen** [troelskn/konstrukt#24]
Hi @troelskn, could you protect the master branch so it can only be updated using pull requests?

**Comment by troelskn** [comment]
Done

**Comment by lsolesen** [comment]
Still not protected. Maybe you need to choose the checkbox (also for admins also)?
